create table tb_ninjaa (id bigserial not null, name varchar(255), taijutsu integer, vila_id bigint, primary key (id));
create table tb_vila (id bigserial not null, name varchar(255), primary key (id));
alter table if exists tb_ninjaa add constraint FKgv6ss3lq45p7k7thdw4q98sxr foreign key (vila_id) references tb_vila;
INSERT INTO tb_vila (name) VALUES ('konohagakure');
INSERT INTO tb_vila (name) VALUES ('Amegakure');
INSERT INTO tb_vila (name) VALUES ('Iwagakure');
INSERT INTO tb_vila (name) VALUES ('Kirigakure');
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Akamaru', 83, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Akita Inuzuka', 12, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Ame', 69, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Ami', 84, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Aniki (Gângster)', 82, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Aoba Yamashiro', 50, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Aoi Rokushō', 96, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Assistente do Escultor de Pedra', 27, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Astrônoma de Konoha', 58, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Asuma Sarutobi', 95, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Baku', 28, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Baku (Anbu)', 63, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Biwako Sarutobi', 74, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Boruto Uzumaki', 29, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Chen', 19, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Chōbee Akimichi', 30, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Corvo de Itachi', 59, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Daikoku Funeno', 29, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Dajimu', 69, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Dan Katō', 66, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Dançarina dos Ventos', 77, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Daruma Izuno', 74, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Dokan', 27, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Dōtō Akimichi', 70, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Ebisu', 98, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Eiki Fūma', 46, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Enra', 30, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Ensui Nara', 60, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Escultor de Pedra', 80, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Esposa de Kisuke', 35, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Fuki', 17, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Futaba', 14, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Fū Yamanaka', 79, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Gamaken', 84, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Gamamaru', 48, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Gamariki', 99, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Gamatatsu', 21, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Garaga', 89, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Gazeru', 66, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Gyokurō Chabashira', 53, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Haguruma', 19, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hajiki', 72, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hako Kuroi', 47, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hakui', 94, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hakui (Médico)', 47, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Harika Aburame', 59, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hayate Gekkō', 56, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hazuki Uchiha', 100, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hiashi Hyūga', 56, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hibari', 11, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hibari Kamakura', 64, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Himawari Uzumaki', 37, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hinata Hyūga (Mundo Genjutsu)', 71, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hinoe', 57, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hiruko (nukenin)', 91, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hiruzen Sarutobi', 68, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hizashi Hyūga', 66, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hotaru (estudante)', 95, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hōsei', 48, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hōshō', 47, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Ibara', 90, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Idate Morino', 33, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Ikkaku Umino', 79, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Inabi Uchiha', 89, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Inaho', 49, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Inojin Yamanaka', 27, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Iroha Hyūga', 90, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Iwabee Yuino', 99, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Iwana Akame', 28, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Iwashi Tatami', 36, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Iō', 54, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Iō (Ninja Médico)', 42, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Jimei', 28, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Jin', 84, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Jiraiya', 81, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Jirō', 21, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kabuto Yakushi', 67, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kaede', 89, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kage (Anbu)', 71, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kagen Uchiha', 63, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kakoi', 71, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kande Inabikari', 15, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kanoe', 50, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kanoto', 72, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kanpō', 11, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kasumi', 48, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Katasuke Tōno', 54, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Keiri', 72, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kido Tsumiki', 34, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kinoto', 86, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Baiu', 77, 2);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Camaleão Gigante', 17, 2);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Fusō', 88, 2);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Fuyō', 80, 2);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Heiji', 46, 2);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kie', 26, 2);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Mubi', 93, 2);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Nagato', 52, 2);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Quimera Gigante', 37, 2);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Ryūsui', 97, 2);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Ugatsu', 76, 2);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Akatsuchi', 25, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Akkun', 68, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Gari', 61, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Han', 74, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Ittan', 42, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Iwazo', 54, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kirara', 64, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kokuō', 85, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kozuchi', 89, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kurobachi', 27, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Mahiru', 15, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Monga', 74, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Morio', 92, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Mū', 32, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Sekiei', 30, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Sekki', 97, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Son Gokū', 23, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Suzumebachi', 17, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Taiseki', 23, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Byakuren', 66, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Chino', 35, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Chōjūrō', 42, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Chūkichi', 37, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Gonbee', 63, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Haku', 42, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hassaku Onomichi', 76, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Jūzō Biwa', 44, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kagura Karatachi', 82, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Karyū', 64, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kiruru', 36, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kisame Hoshigaki', 47, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kosuke', 92, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kushimaru Kuriarare', 65, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kyohō Fuefuki', 33, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Mangetsu Hōzuki', 89, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Marisco Gigante', 25, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Mei Terumī', 100, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Meizu', 74, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Miru', 86, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Misuno', 14, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Mukai Kohinata', 37, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Obito Uchiha', 26, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Raiga Kurosuki', 49, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Saiken', 94, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Suigetsu Hōzuki', 83, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Suiren (Kiri)', 35, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Tenzen', 17, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Terceiro Mizukage', 60, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Tetsu', 46, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Tsurugi', 24, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Utakata', 31, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Zabuza Momochi', 88, 4);
create table tb_ninjaa (id bigserial not null, name varchar(255), taijutsu integer, vila_id bigint, primary key (id));
create table tb_vila (id bigserial not null, name varchar(255), primary key (id));
alter table tb_ninjaa add constraint FKgv6ss3lq45p7k7thdw4q98sxr foreign key (vila_id) references tb_vila;
INSERT INTO tb_vila (name) VALUES ('konohagakure');
INSERT INTO tb_vila (name) VALUES ('Amegakure');
INSERT INTO tb_vila (name) VALUES ('Iwagakure');
INSERT INTO tb_vila (name) VALUES ('Kirigakure');
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Akamaru', 83, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Akita Inuzuka', 12, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Ame', 69, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Ami', 84, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Aniki (Gângster)', 82, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Aoba Yamashiro', 50, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Aoi Rokushō', 96, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Assistente do Escultor de Pedra', 27, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Astrônoma de Konoha', 58, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Asuma Sarutobi', 95, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Baku', 28, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Baku (Anbu)', 63, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Biwako Sarutobi', 74, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Boruto Uzumaki', 29, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Chen', 19, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Chōbee Akimichi', 30, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Corvo de Itachi', 59, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Daikoku Funeno', 29, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Dajimu', 69, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Dan Katō', 66, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Dançarina dos Ventos', 77, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Daruma Izuno', 74, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Dokan', 27, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Dōtō Akimichi', 70, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Ebisu', 98, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Eiki Fūma', 46, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Enra', 30, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Ensui Nara', 60, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Escultor de Pedra', 80, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Esposa de Kisuke', 35, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Fuki', 17, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Futaba', 14, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Fū Yamanaka', 79, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Gamaken', 84, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Gamamaru', 48, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Gamariki', 99, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Gamatatsu', 21, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Garaga', 89, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Gazeru', 66, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Gyokurō Chabashira', 53, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Haguruma', 19, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hajiki', 72, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hako Kuroi', 47, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hakui', 94, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hakui (Médico)', 47, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Harika Aburame', 59, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hayate Gekkō', 56, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hazuki Uchiha', 100, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hiashi Hyūga', 56, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hibari', 11, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hibari Kamakura', 64, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Himawari Uzumaki', 37, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hinata Hyūga (Mundo Genjutsu)', 71, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hinoe', 57, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hiruko (nukenin)', 91, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hiruzen Sarutobi', 68, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hizashi Hyūga', 66, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hotaru (estudante)', 95, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hōsei', 48, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hōshō', 47, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Ibara', 90, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Idate Morino', 33, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Ikkaku Umino', 79, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Inabi Uchiha', 89, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Inaho', 49, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Inojin Yamanaka', 27, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Iroha Hyūga', 90, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Iwabee Yuino', 99, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Iwana Akame', 28, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Iwashi Tatami', 36, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Iō', 54, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Iō (Ninja Médico)', 42, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Jimei', 28, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Jin', 84, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Jiraiya', 81, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Jirō', 21, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kabuto Yakushi', 67, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kaede', 89, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kage (Anbu)', 71, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kagen Uchiha', 63, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kakoi', 71, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kande Inabikari', 15, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kanoe', 50, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kanoto', 72, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kanpō', 11, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kasumi', 48, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Katasuke Tōno', 54, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Keiri', 72, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kido Tsumiki', 34, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kinoto', 86, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Baiu', 77, 2);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Camaleão Gigante', 17, 2);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Fusō', 88, 2);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Fuyō', 80, 2);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Heiji', 46, 2);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kie', 26, 2);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Mubi', 93, 2);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Nagato', 52, 2);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Quimera Gigante', 37, 2);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Ryūsui', 97, 2);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Ugatsu', 76, 2);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Akatsuchi', 25, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Akkun', 68, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Gari', 61, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Han', 74, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Ittan', 42, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Iwazo', 54, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kirara', 64, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kokuō', 85, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kozuchi', 89, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kurobachi', 27, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Mahiru', 15, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Monga', 74, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Morio', 92, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Mū', 32, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Sekiei', 30, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Sekki', 97, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Son Gokū', 23, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Suzumebachi', 17, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Taiseki', 23, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Byakuren', 66, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Chino', 35, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Chōjūrō', 42, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Chūkichi', 37, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Gonbee', 63, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Haku', 42, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hassaku Onomichi', 76, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Jūzō Biwa', 44, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kagura Karatachi', 82, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Karyū', 64, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kiruru', 36, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kisame Hoshigaki', 47, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kosuke', 92, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kushimaru Kuriarare', 65, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kyohō Fuefuki', 33, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Mangetsu Hōzuki', 89, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Marisco Gigante', 25, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Mei Terumī', 100, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Meizu', 74, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Miru', 86, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Misuno', 14, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Mukai Kohinata', 37, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Obito Uchiha', 26, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Raiga Kurosuki', 49, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Saiken', 94, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Suigetsu Hōzuki', 83, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Suiren (Kiri)', 35, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Tenzen', 17, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Terceiro Mizukage', 60, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Tetsu', 46, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Tsurugi', 24, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Utakata', 31, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Zabuza Momochi', 88, 4);
create table tb_ninjaa (id bigserial not null, name varchar(255), taijutsu integer, vila_id bigint, primary key (id));
create table tb_vila (id bigserial not null, name varchar(255), primary key (id));
alter table tb_ninjaa add constraint FKgv6ss3lq45p7k7thdw4q98sxr foreign key (vila_id) references tb_vila;
INSERT INTO tb_vila (name) VALUES ('konohagakure');
INSERT INTO tb_vila (name) VALUES ('Amegakure');
INSERT INTO tb_vila (name) VALUES ('Iwagakure');
INSERT INTO tb_vila (name) VALUES ('Kirigakure');
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Akamaru', 83, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Akita Inuzuka', 12, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Ame', 69, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Ami', 84, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Aniki (Gângster)', 82, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Aoba Yamashiro', 50, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Aoi Rokushō', 96, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Assistente do Escultor de Pedra', 27, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Astrônoma de Konoha', 58, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Asuma Sarutobi', 95, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Baku', 28, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Baku (Anbu)', 63, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Biwako Sarutobi', 74, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Boruto Uzumaki', 29, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Chen', 19, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Chōbee Akimichi', 30, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Corvo de Itachi', 59, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Daikoku Funeno', 29, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Dajimu', 69, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Dan Katō', 66, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Dançarina dos Ventos', 77, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Daruma Izuno', 74, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Dokan', 27, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Dōtō Akimichi', 70, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Ebisu', 98, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Eiki Fūma', 46, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Enra', 30, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Ensui Nara', 60, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Escultor de Pedra', 80, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Esposa de Kisuke', 35, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Fuki', 17, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Futaba', 14, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Fū Yamanaka', 79, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Gamaken', 84, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Gamamaru', 48, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Gamariki', 99, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Gamatatsu', 21, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Garaga', 89, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Gazeru', 66, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Gyokurō Chabashira', 53, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Haguruma', 19, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hajiki', 72, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hako Kuroi', 47, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hakui', 94, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hakui (Médico)', 47, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Harika Aburame', 59, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hayate Gekkō', 56, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hazuki Uchiha', 100, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hiashi Hyūga', 56, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hibari', 11, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hibari Kamakura', 64, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Himawari Uzumaki', 37, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hinata Hyūga (Mundo Genjutsu)', 71, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hinoe', 57, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hiruko (nukenin)', 91, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hiruzen Sarutobi', 68, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hizashi Hyūga', 66, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hotaru (estudante)', 95, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hōsei', 48, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hōshō', 47, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Ibara', 90, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Idate Morino', 33, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Ikkaku Umino', 79, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Inabi Uchiha', 89, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Inaho', 49, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Inojin Yamanaka', 27, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Iroha Hyūga', 90, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Iwabee Yuino', 99, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Iwana Akame', 28, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Iwashi Tatami', 36, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Iō', 54, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Iō (Ninja Médico)', 42, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Jimei', 28, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Jin', 84, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Jiraiya', 81, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Jirō', 21, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kabuto Yakushi', 67, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kaede', 89, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kage (Anbu)', 71, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kagen Uchiha', 63, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kakoi', 71, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kande Inabikari', 15, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kanoe', 50, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kanoto', 72, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kanpō', 11, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kasumi', 48, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Katasuke Tōno', 54, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Keiri', 72, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kido Tsumiki', 34, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kinoto', 86, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Baiu', 77, 2);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Camaleão Gigante', 17, 2);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Fusō', 88, 2);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Fuyō', 80, 2);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Heiji', 46, 2);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kie', 26, 2);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Mubi', 93, 2);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Nagato', 52, 2);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Quimera Gigante', 37, 2);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Ryūsui', 97, 2);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Ugatsu', 76, 2);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Akatsuchi', 25, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Akkun', 68, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Gari', 61, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Han', 74, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Ittan', 42, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Iwazo', 54, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kirara', 64, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kokuō', 85, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kozuchi', 89, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kurobachi', 27, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Mahiru', 15, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Monga', 74, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Morio', 92, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Mū', 32, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Sekiei', 30, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Sekki', 97, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Son Gokū', 23, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Suzumebachi', 17, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Taiseki', 23, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Byakuren', 66, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Chino', 35, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Chōjūrō', 42, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Chūkichi', 37, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Gonbee', 63, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Haku', 42, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hassaku Onomichi', 76, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Jūzō Biwa', 44, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kagura Karatachi', 82, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Karyū', 64, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kiruru', 36, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kisame Hoshigaki', 47, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kosuke', 92, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kushimaru Kuriarare', 65, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kyohō Fuefuki', 33, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Mangetsu Hōzuki', 89, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Marisco Gigante', 25, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Mei Terumī', 100, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Meizu', 74, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Miru', 86, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Misuno', 14, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Mukai Kohinata', 37, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Obito Uchiha', 26, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Raiga Kurosuki', 49, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Saiken', 94, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Suigetsu Hōzuki', 83, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Suiren (Kiri)', 35, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Tenzen', 17, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Terceiro Mizukage', 60, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Tetsu', 46, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Tsurugi', 24, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Utakata', 31, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Zabuza Momochi', 88, 4);
create table tb_ninjaa (id bigserial not null, name varchar(255), taijutsu integer, vila_id bigint, primary key (id));
create table tb_vila (id bigserial not null, name varchar(255), primary key (id));
alter table if exists tb_ninjaa add constraint FKgv6ss3lq45p7k7thdw4q98sxr foreign key (vila_id) references tb_vila;
INSERT INTO tb_vila (name) VALUES ('konohagakure');
INSERT INTO tb_vila (name) VALUES ('Amegakure');
INSERT INTO tb_vila (name) VALUES ('Iwagakure');
INSERT INTO tb_vila (name) VALUES ('Kirigakure');
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Akamaru', 83, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Akita Inuzuka', 12, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Ame', 69, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Ami', 84, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Aniki (Gângster)', 82, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Aoba Yamashiro', 50, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Aoi Rokushō', 96, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Assistente do Escultor de Pedra', 27, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Astrônoma de Konoha', 58, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Asuma Sarutobi', 95, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Baku', 28, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Baku (Anbu)', 63, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Biwako Sarutobi', 74, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Boruto Uzumaki', 29, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Chen', 19, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Chōbee Akimichi', 30, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Corvo de Itachi', 59, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Daikoku Funeno', 29, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Dajimu', 69, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Dan Katō', 66, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Dançarina dos Ventos', 77, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Daruma Izuno', 74, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Dokan', 27, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Dōtō Akimichi', 70, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Ebisu', 98, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Eiki Fūma', 46, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Enra', 30, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Ensui Nara', 60, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Escultor de Pedra', 80, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Esposa de Kisuke', 35, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Fuki', 17, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Futaba', 14, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Fū Yamanaka', 79, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Gamaken', 84, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Gamamaru', 48, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Gamariki', 99, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Gamatatsu', 21, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Garaga', 89, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Gazeru', 66, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Gyokurō Chabashira', 53, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Haguruma', 19, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hajiki', 72, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hako Kuroi', 47, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hakui', 94, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hakui (Médico)', 47, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Harika Aburame', 59, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hayate Gekkō', 56, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hazuki Uchiha', 100, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hiashi Hyūga', 56, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hibari', 11, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hibari Kamakura', 64, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Himawari Uzumaki', 37, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hinata Hyūga (Mundo Genjutsu)', 71, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hinoe', 57, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hiruko (nukenin)', 91, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hiruzen Sarutobi', 68, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hizashi Hyūga', 66, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hotaru (estudante)', 95, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hōsei', 48, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hōshō', 47, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Ibara', 90, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Idate Morino', 33, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Ikkaku Umino', 79, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Inabi Uchiha', 89, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Inaho', 49, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Inojin Yamanaka', 27, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Iroha Hyūga', 90, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Iwabee Yuino', 99, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Iwana Akame', 28, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Iwashi Tatami', 36, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Iō', 54, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Iō (Ninja Médico)', 42, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Jimei', 28, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Jin', 84, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Jiraiya', 81, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Jirō', 21, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kabuto Yakushi', 67, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kaede', 89, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kage (Anbu)', 71, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kagen Uchiha', 63, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kakoi', 71, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kande Inabikari', 15, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kanoe', 50, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kanoto', 72, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kanpō', 11, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kasumi', 48, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Katasuke Tōno', 54, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Keiri', 72, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kido Tsumiki', 34, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kinoto', 86, 1);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Baiu', 77, 2);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Camaleão Gigante', 17, 2);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Fusō', 88, 2);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Fuyō', 80, 2);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Heiji', 46, 2);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kie', 26, 2);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Mubi', 93, 2);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Nagato', 52, 2);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Quimera Gigante', 37, 2);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Ryūsui', 97, 2);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Ugatsu', 76, 2);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Akatsuchi', 25, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Akkun', 68, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Gari', 61, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Han', 74, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Ittan', 42, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Iwazo', 54, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kirara', 64, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kokuō', 85, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kozuchi', 89, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kurobachi', 27, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Mahiru', 15, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Monga', 74, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Morio', 92, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Mū', 32, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Sekiei', 30, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Sekki', 97, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Son Gokū', 23, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Suzumebachi', 17, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Taiseki', 23, 3);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Byakuren', 66, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Chino', 35, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Chōjūrō', 42, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Chūkichi', 37, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Gonbee', 63, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Haku', 42, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Hassaku Onomichi', 76, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Jūzō Biwa', 44, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kagura Karatachi', 82, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Karyū', 64, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kiruru', 36, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kisame Hoshigaki', 47, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kosuke', 92, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kushimaru Kuriarare', 65, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Kyohō Fuefuki', 33, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Mangetsu Hōzuki', 89, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Marisco Gigante', 25, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Mei Terumī', 100, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Meizu', 74, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Miru', 86, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Misuno', 14, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Mukai Kohinata', 37, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Obito Uchiha', 26, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Raiga Kurosuki', 49, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Saiken', 94, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Suigetsu Hōzuki', 83, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Suiren (Kiri)', 35, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Tenzen', 17, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Terceiro Mizukage', 60, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Tetsu', 46, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Tsurugi', 24, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Utakata', 31, 4);
INSERT INTO tb_ninjaa (name, taijutsu, vila_id) VALUES ('Zabuza Momochi', 88, 4);
